---
abstract: 'Building freeimage library L<http://freeimage.sourceforge.net/>'
author:
  - 'KMX <kmx@cpan.org>'
build_requires:
  ExtUtils::Command: 0
  File::Path: 0
  File::ShareDir: 0
  File::Spec: 0
  Module::Build: 0
  Test::More: 0
  perl: 5.008
configure_requires:
  ExtUtils::Command: 0
  File::Path: 0
  File::ShareDir: 0
  File::Spec: 0
  Module::Build: 0
  perl: 5.008
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-FreeImage
no_index:
  directory:
    - src
provides:
  Alien::FreeImage:
    file: lib/Alien/FreeImage.pm
    version: 0.007
requires:
  File::ShareDir: 1.00
  File::Spec: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-FreeImage
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kmx/alien-freeimage
version: 0.007
